spring:
  application:
    name: miniDooray-AccountAPI

  session:
    store-type: none  # AccountAPI는 REST API라 세션 불필요 (SPRING_SESSION 테이블 오류 방지)

  servlet:
    encoding:
      charset: UTF-8
      force: true

#  datasource:
##    url: jdbc:mysql://10.116.64.14:13306/nhn_academy_46?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://s4.java21.net:13306/nhn_academy_46?serverTimezone=Asia/Seoul
#    username: nhn_academy_46
#    password: s193!UhKNBc3X9(8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: update # \uAC1C\uBC1C\uC6A9
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: false # SQL \uB85C\uADF8 \uBCF4\uAE30

server:
  port: 8081
